# -*- coding: utf-8 -*-
"""fuse_data-temp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8Ejse2A7BxBR6lYy4GwUfIAfifOhkqC
"""

#Quentin
from google.colab import files

#Add output.csv
uploaded = files.upload()

#Add temperature.csv
uploaded = files.upload()

import pandas as pd

data = pd.read_csv("/content/output.csv")
temp = pd.read_csv("/content/temperature.csv")

data.head()

temp.head()

dic = temp.set_index('date')['temp'].to_dict()
print(dic)

#Manual adding for temp not in files, for the first of january 2020-2025

dic['2020-01-01'] = 245.707594

dic['2021-01-01'] = 259.458771

dic['2022-01-01'] = 247.323099

dic['2023-01-01'] = 250.573624

dic['2024-01-01'] = 250.573624

dic['2025-01-01'] = 247.160217

data["temp"] = data["time"].map(dic)

data.head()

data.to_csv("data.csv")

data.isna().sum()